workflow:
  rules:
    - if: $CI_MERGE_REQUEST_ID
      when: never
    - when: always

stages:
  - triggers

benchmarks:
  stage: triggers
  trigger:
    include: benchmarks/.gitlab-ci.yml
    strategy: depend
  rules:
    - if: "$CI_COMMIT_TAG"
    - changes:
      - benchmarks/*
    - when: manual
      allow_failure: true
  