apiVersion: batch/v1
kind: Job
metadata:
  name: theodolite-kotlin-test
spec:
  template:
    spec:
      volumes:
      - name: theodolite-pv-storage
        persistentVolumeClaim:
          claimName: theodolite-pv-claim
      containers:
        - name: lag-analysis
          image: ghcr.io/cau-se/theodolite-slo-checker-lag-trend:theodolite-kotlin-latest
          ports:
          - containerPort: 80
            name: analysis
        - name: theodolite
          image: benediktwetzel/theodolite-test #ghcr.io/cau-se/theodolite:theodolite-kotlin-latest
          imagePullPolicy: Always
          env:
            - name: NAMESPACE
              value: theodolite-she
            - name: MODE
              value: yaml-executor
            - name: THEODOLITE_EXECUTION
              value: /etc/execution/example-execution-yaml-resource.yaml
            - name: THEODOLITE_BENCHMARK
              value: /etc/benchmark/example-benchmark-yaml-resource.yaml
            - name: THEODOLITE_APP_RESOURCES
              value: /etc/app-resources
          volumeMounts:
          - name: app-resources
            mountPath: /etc/app-resources
          - name: benchmark
            mountPath: /etc/benchmark
          - name: execution
            mountPath: /etc/execution
        #  -  name: theodolite-pv-storage
        #     mountPath: "/deployments"
      restartPolicy: Never
      # Uncomment if RBAC is enabled and configured
      serviceAccountName: theodolite
      volumes:
        - name: app-resources
          configMap:
            name: app-resources-configmap
        - name: benchmark
          configMap:
            name: benchmark-configmap
        - name: execution
          configMap:
            name: execution-configmap
  backoffLimit: 4