apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: titan-ccp-aggregation

# Use all resources to compose them into one file
resources:
  - aggregation-deployment.yaml
  - aggregation-service.yaml
  - service-monitor.yaml
  - jmx-configmap.yaml
