apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: benchmarks.theodolite.com
spec:
  group: theodolite.com
  version: v1alpha1
  names:
    kind: benchmark
    plural: benchmarks
  scope: Namespaced
  subresources:
    status: {}