{{- if .Values.kafkaClient.enabled -}}
apiVersion: v1
kind: Pod
metadata:
  name: kafka-client
spec:
  containers:
  - name: kafka-client
    image: confluentinc/cp-enterprise-kafka:5.4.0
    command:
      - sh
      - -c
      - "exec tail -f /dev/null"
  {{- with .Values.nodeSelector }}
  nodeSelector:
    {{- toYaml . | nindent 8 }}
  {{- end }}
{{- end }}