apiVersion: v1
kind: Pod
metadata:
  name: theodolite-results-access
spec:
  restartPolicy: Always
  containers:
  - name: theodolite-results-access
    image: busybox:latest
    command:
    - sh
    - -c
    - exec tail -f /dev/null
    volumeMounts:
    - mountPath: /app/results
      name: theodolite-pv-storage
  volumes:
    - name: theodolite-pv-storage
      persistentVolumeClaim:
        claimName: theodolite-pv-claim
