apiVersion: apps/v1
kind: Deployment
metadata:
  name: theodolite-results-access
  labels:
    app: theodolite-results-access
spec:
  replicas: 1
  selector:
    matchLabels:
      app: theodolite-results-access
  template:
    metadata:
      labels:
        app: theodolite-results-access
    spec:
      containers:
      - name: theodolite-results-access
        image: busybox:latest
        command:
        - sh
        - -c
        - exec tail -f /dev/null
        volumeMounts:
        - mountPath: /app/results
          name: theodolite-pv-storage
      volumes:
        - name: theodolite-pv-storage
          persistentVolumeClaim:
            claimName: theodolite-pv-claim
