apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
spec:
  serviceAccountName: prometheus
  serviceMonitorSelector:
    matchLabels:
      #app: cp-kafka
      appScope: titan-ccp
  resources:
    requests:
      memory: 400Mi
  #scrapeInterval: 1s
  enableAdminAPI: true