apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: theodolite
rules:
  - apiGroups:
    - apps
    resources:
    - deployments
    verbs:
    - delete
    - list
    - get
    - create
  - apiGroups:
    - ""
    resources:
    - services
    - pods
    - servicemonitors
    - configmaps
    verbs:
    - delete
    - list
    - get
    - create
  - apiGroups:
    - ""
    resources:
    - pods/exec
    verbs:
    - create
    - get
  - apiGroups:
    - monitoring.coreos.com
    resources:
    - servicemonitors
    verbs:
    - delete
    - list
    - create