name: "uc1-kstreams"
appResource:
  - "uc1-kstreams-deployment.yaml"
  - "aggregation-service.yaml"
  - "jmx-configmap.yaml"
  - "uc1-service-monitor.yaml"
loadGenResource:
  - "uc1-load-generator-deployment.yaml"
  - "uc1-load-generator-service.yaml"
resourceTypes:
  - typeName: "Instances"
    patchers:
      - type: "ReplicaPatcher"
        resource: "uc1-kstreams-deployment.yaml"
loadTypes:
  - typeName: "NumSensors"
    patchers:
      - type: "EnvVarPatcher"
        resource: "uc1-load-generator-deployment.yaml"
        config:
          - key: "variableName"
            value: "NUM_SENSORS"
          - key: "container"
            value: "workload-generator"
      - type: "NumSensorsLoadGeneratorReplicaPatcher"
        resource: "uc1-load-generator-deployment.yaml"
        config:
          - key: "loadGenMaxRecords"
            value: "15000"
kafkaConfig:
  bootstrapServer: "localhost:9092"
  topics:
    - name: "input"
      numPartitions: 40
      replicationFactor: 1
    - name: "theodolite-.*"
      removeOnly: True