image: openjdk:11-jdk

include:
  - template: Code-Quality.gitlab-ci.yml

stages:
  - build
  - test
  - check
  #- package

before_script:
  - cd theodolite-quarkus
  - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

compile:
  stage: build
  tags:
    - exec-docker
  script:
    - ./gradlew build

code_quality:
  tags:
    - exec-docker


test:
  stage: test
  tags:
    - exec-docker
  script:
    - ./gradlew test --stacktrace

ktlint:
  stage: check
  tags:
    - exec-docker
  script:
    - ./gradlew ktlintCheck --continue

.detekt: 
  stage: check
  tags:
    - exec-docker
  script:
     - ./gradlew detekt --continue