{{- if .Values.executionCRD.create -}}
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: executions.theodolite.com
spec:
  group: theodolite.com
  version: v1alpha1
  names:
    kind: execution
    plural: executions
  scope: Namespaced
  subresources:
    status: {}
{{- end }}