{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "theodolite.fullname" . }}
rules:
  - apiGroups:
    - apps
    resources:
    - deployments
    verbs:
    - delete
    - list
    - get
    - create
    - update
  - apiGroups:
    - ""
    resources:
    - services
    - pods
    - configmaps
    verbs:
    - update
    - delete
    - list
    - get
    - create
  - apiGroups:
    - ""
    resources:
    - pods/exec
    verbs:
    - create
    - get
  - apiGroups:
    - monitoring.coreos.com
    resources:
    - servicemonitors
    verbs:
    - update
    - delete
    - list
    - create
  {{- if .Values.operator.enabled }}
  - apiGroups:
    - theodolite.com
    resources: 
    - executions
    - benchmarks
    verbs:
    - delete
    - list
    - get
    - create
    - watch
    - update
    - patch
  {{- end }}
{{- end }}