{{- if .Values.operator.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "theodolite.fullname" . }}-operator
spec:
  selector:
    matchLabels:
      app: {{ include "theodolite.fullname" . }}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ include "theodolite.fullname" . }}
    spec:
      terminationGracePeriodSeconds: 0
      serviceAccountName:  {{ include "theodolite.serviceAccountName" . }}
      securityContext:
        runAsUser: 0 # Set the permissions for write access to the volumes.
      containers:
        - name: theodolite
          image: ghcr.io/cau-se/theodolite:theodolite-kotlin-latest
          imagePullPolicy: Always
          env:
            - name: NAMESPACE
              value: {{ .Release.Namespace }}
            - name: MODE
              value: operator
            - name: THEODOLITE_APP_RESOURCES
              value: "./benchmark-resources"
            - name: RESULTS_FOLDER
              value: "results"
          volumeMounts:
            - name: theodolite-pv-storage
              mountPath: "/deployments/results"
            - name: benchmark-resources-uc1-kstreams
              mountPath: /deployments/benchmark-resources/uc1-kstreams
            - name: benchmark-resources-uc2-kstreams
              mountPath: /deployments/benchmark-resources/uc2-kstreams
            - name: benchmark-resources-uc3-kstreams
              mountPath: /deployments/benchmark-resources/uc3-kstreams
            - name: benchmark-resources-uc4-kstreams
              mountPath: /deployments/benchmark-resources/uc4-kstreams
            - name: benchmark-resources-uc1-flink
              mountPath: /deployments/benchmark-resources/uc1-flink
            - name: benchmark-resources-uc2-flink
              mountPath: /deployments/benchmark-resources/uc2-flink
            - name: benchmark-resources-uc3-flink
              mountPath: /deployments/benchmark-resources/uc3-flink
            - name: benchmark-resources-uc4-flink
              mountPath: /deployments/benchmark-resources/uc4-flink
        - name: lag-analysis
          image: ghcr.io/cau-se/theodolite-slo-checker-lag-trend:theodolite-kotlin-latest
          imagePullPolicy: Always
          ports:
          - containerPort: 80
            name: analysis
          env:
          - name: LOG_LEVEL
            value: INFO
        - name: results-access
          image: busybox:stable
          command:
          - sh
          - -c
          - exec tail -f /dev/null
          volumeMounts:
          - mountPath: /results
            name: theodolite-pv-storage
      volumes:
      - name: theodolite-pv-storage
        persistentVolumeClaim:
          claimName: theodolite-pv-claim
      - name: benchmark-resources-uc1-kstreams
        configMap:
          name: benchmark-resources-uc1-kstreams
          optional: true
      - name: benchmark-resources-uc2-kstreams
        configMap:
          name: benchmark-resources-uc2-kstreams
          optional: true
      - name: benchmark-resources-uc3-kstreams
        configMap:
          name: benchmark-resources-uc3-kstreams
          optional: true
      - name: benchmark-resources-uc4-kstreams
        configMap:
          name: benchmark-resources-uc4-kstreams
          optional: true
      - name: benchmark-resources-uc1-flink
        configMap:
          name: benchmark-resources-uc1-flink
          optional: true
      - name: benchmark-resources-uc2-flink
        configMap:
          name: benchmark-resources-uc2-flink
          optional: true
      - name: benchmark-resources-uc3-flink
        configMap:
          name: benchmark-resources-uc3-flink
          optional: true
      - name: benchmark-resources-uc4-flink
        configMap:
          name: benchmark-resources-uc4-flink
          optional: true
{{- end }}
